version: 2.1
executors:
  default:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Install .NET Core SDK
          command: |
            curl -SL --output dotnet-install.sh https://dot.net/v1/dotnet-install.sh
            chmod +x dotnet-install.sh
            ./dotnet-install.sh --install-dir /usr/share/dotnet --version 6.0 --no-path
            ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
            dotnet --version  # Verify installation
      - run:
          name: Run Selenium Tests
          command: dotnet test --filter Category=Login
      - run:
          name: Modify report CSS
          command: |
            sed -i 's#http://cdn.jsdelivr.net/gh/extent-framework/extent-github-cdn@ff53917fbbdb5ef820abbbe4d199a6942dc771ff/v3html/css/extent.css#extent.css#g' /home/circleci/project/test-output/HtmlReport/ExtentHtml.html
            sed -i 's#http://cdn.jsdelivr.net/gh/extent-framework/extent-github-cdn@ff53917fbbdb5ef820abbbe4d199a6942dc771ff/v3html/js/extent.js#extent.js#g' /home/circleci/project/test-output/HtmlReport/ExtentHtml.html
            cd /home/circleci/project/test-output/HtmlReport
            cat ExtentHtml.html
            ls
      - store_artifacts:
          path: test-output/HtmlReport
          destination: extent-reports
      - store_test_results:
          path: test-output/HtmlReport

workflows:
  version: 2
  build-test:
    jobs:
      - build
