version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: Install .NET Core SDK
          command: |
            sudo curl -LO https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get update
            sudo apt-get install -y apt-transport-https
            sudo apt-get update
            sudo apt-get install -y dotnet-sdk-3.1
      - run:
          name: Install Dependencies
          command: |
            sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | tee -a /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update && apt-get install -y google-chrome-stable
            
            # Download and set up ChromeDriver
            wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/linux64/chromedriver-linux64.zip
            unzip chromedriver-linux64.zip
            sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/chromedriver

            # Install GeckoDriver
            wget -N https://github.com/mozilla/geckodriver/releases/download/v0.31.0/geckodriver-v0.31.0-linux64.tar.gz
            tar -xzf geckodriver-v0.31.0-linux64.tar.gz
            sudo mv geckodriver /usr/local/bin/
            sudo chmod +x /usr/local/bin/geckodriver

            chmod +x /root/project/selenium_specflow_c_sharp/bin/Debug/net6.0/selenium-manager/linux/selenium-manager
      - run:
          name: Run Selenium Tests
          command: dotnet test --filter Category=Login
      - run:
          name: Modify report CSS
          command: |
            sed -i 's#http://cdn.jsdelivr.net/gh/extent-framework/extent-github-cdn@ff53917fbbdb5ef820abbbe4d199a6942dc771ff/v3html/css/extent.css#extent.css#g' /home/circleci/project/test-output/HtmlReport/ExtentHtml.html
            sed -i 's#http://cdn.jsdelivr.net/gh/extent-framework/extent-github-cdn@ff53917fbbdb5ef820abbbe4d199a6942dc771ff/v3html/js/extent.js#extent.js#g' /home/circleci/project/test-output/HtmlReport/ExtentHtml.html
            cd /home/circleci/project/test-output/HtmlReport
            cat ExtentHtml.html
            ls
      - store_artifacts:
          path: test-output/HtmlReport
          destination: extent-reports
      - store_test_results:
          path: test-output/HtmlReport

workflows:
  version: 2
  build-test:
    jobs:
      - build