version: 2.1

executors:
  default:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1

    steps:
      - checkout
      - run:
          name: Install Chrome and ChromeDriver
          command: |
            apt-get update && apt-get install -y curl
            curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | tee -a /etc/apt/sources.list.d/google-chrome.list
            apt-get update && apt-get install -y google-chrome-stable

            # Install ChromeDriver
            CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | cut -d '.' -f 1)
            wget -N https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/linux64/chromedriver-linux64.zip
            unzip chromedriver_linux64.zip -d ~/bin
            mv ~/bin/chromedriver /usr/local/bin/chromedriver
            chmod +x /usr/local/bin/chromedriver

      - run:
          name: Install GeckoDriver
          command: |
            wget -N https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
            tar -xzf geckodriver-v0.33.0-linux64.tar.gz
            mv geckodriver /usr/local/bin/
            chmod +x /usr/local/bin/geckodriver

      - run:
          name: Run Selenium Tests
          command: dotnet test --filter Category=Login

      # Additional steps for modifying report CSS, storing artifacts, and test results
      - run:
          name: Modify report CSS
          command: |
            sed -i 's#http://cdn.jsdelivr.net/gh/extent-framework/extent-github-cdn@ff53917fbbdb5ef820abbbe4d199a6942dc771ff/v3html/css/extent.css#extent.css#g' /home/circleci/project/test-output/HtmlReport/ExtentHtml.html
            sed -i 's#http://cdn.jsdelivr.net/gh/extent-framework/extent-github-cdn@ff53917fbbdb5ef820abbbe4d199a6942dc771ff/v3html/js/extent.js#extent.js#g' /home/circleci/project/test-output/HtmlReport/ExtentHtml.html
            cd /home/circleci/project/test-output/HtmlReport
            cat ExtentHtml.html
            ls

      - store_artifacts:
          path: test-output/HtmlReport
          destination: extent-reports

      - store_test_results:
          path: test-output/HtmlReport

workflows:
  version: 2
  build-test:
    jobs:
      - build
